#!/usr/bin/env bash
set -euo pipefail

NS=${NS:-infra-learning}
DEPLOY=${DEPLOY:-ray-vllm-pd-decode-ab-qwen36-27b}
EXPERIMENT_ID=${EXPERIMENT_ID:?set EXPERIMENT_ID}
RUN_ID=${RUN_ID:?set RUN_ID}
ENABLED=${ENABLED:-true}
CONFIG_ID=qwen36-1p2d-d2-full-decode-only-async-v1
RAW_DIR=/servingrom-results/$EXPERIMENT_ID/$RUN_ID/raw/proxy

kubectl -n "$NS" set env deployment/"$DEPLOY" \
  SERVINGROM_TELEMETRY_ENABLED="$ENABLED" \
  SERVINGROM_EXPERIMENT_ID="$EXPERIMENT_ID" \
  SERVINGROM_RUN_ID="$RUN_ID" \
  SERVINGROM_CONFIG_ID="$CONFIG_ID" \
  SERVINGROM_COMPONENT=proxy \
  SERVINGROM_OUTPUT_DIR="$RAW_DIR" \
  SERVINGROM_QUEUE_CAPACITY="${SERVINGROM_QUEUE_CAPACITY:-65536}" \
  SERVINGROM_BATCH_SIZE="${SERVINGROM_BATCH_SIZE:-1024}" \
  SERVINGROM_FLUSH_INTERVAL_MS="${SERVINGROM_FLUSH_INTERVAL_MS:-250}" \
  SERVINGROM_MAX_FILE_BYTES="${SERVINGROM_MAX_FILE_BYTES:-268435456}"

kubectl -n "$NS" rollout status deployment/"$DEPLOY" --timeout=60m
